Update Jenkinsfile

diff --git a/sample/Jenkinsfile b/sample/Jenkinsfile
--- a/sample/Jenkinsfile
+++ b/sample/Jenkinsfile
@@ -34,16 +34,33 @@ pipeline {
 
 
 
-        stage('Build Docker Image') {
-            steps {
-                script {
-                    sh '''
-                    echo "Building Docker image"
-                    docker build -t ${LOCAL_REGISTRY}/python-app:${IMAGE_TAG} -f sample/Dockerfile .
-                    '''
-                }
+        stage('Setup Google Cloud') {
+    steps {
+        script {
+            withCredentials([file(credentialsId: 'google-credentials', variable: 'GCLOUD_KEY_FILE')]) {
+                sh '''
+                echo "GCLOUD_KEY_FILE is set to $GCLOUD_KEY_FILE"
+                ls -l $GCLOUD_KEY_FILE
+
+                echo "Checking /tmp permissions"
+                ls -ld /tmp
+
+                echo "Testing write access"
+                touch /tmp/testfile
+                rm /tmp/testfile
+
+                echo "Copying Google Cloud key to /tmp"
+                cp $GCLOUD_KEY_FILE /tmp/gcloud-key.json
+
+                echo "Listing files in /tmp after copy"
+                ls -l /tmp
+                echo "Validating JSON file"
+                jq . /tmp/gcloud-key.json || echo "Invalid JSON format"
+                '''
             }
         }
+    }
+}
 
         stage('Push Docker Image to Local Registry') {
             steps {
